export enum PageID {
  CameraPage = 'camera_page',
  StoryPage = 'story_page',
  CreateStoryPage = 'create_story_page',
  WildCardPage = '*',
  social_home_page = 'social_home_page',
  global_search_page = 'global_search_page',
  post_detail_page = 'post_detail_page',
  social_global_search_page = 'social_global_search_page',
  post_composer_page = 'post_composer_page',
  select_post_target_page = 'select_post_target_page',
  select_story_target_page = 'select_story_target_page',
  all_categories_page = 'all_categories_page',
  communities_by_category_page = 'communities_by_category_page',
  community_profile_page = 'community_profile_page',
  livestream_post_target_selection_page = 'livestream_post_target_selection_page',
  create_livestream_page = 'create_livestream_page',
  livestream_player_page = 'livestream_player_page',
  livestream_terminated_page = 'livestream_terminated_page',
  select_poll_target_page = 'select_poll_target_page',
  poll_post_composer_page = 'poll_post_composer_page',
  community_setup_page = 'community_setup_page',
  community_setting_page = 'community_setting_page',
  pending_request_page = 'pending_request_page',
  user_profile_page = 'user_profile_page',
  edit_user_profile_page = 'edit_user_profile_page',
  create_user_profile_page = 'create_user_profile_page',
  blocked_users_page = 'blocked_users_page',
  user_relationship_page = 'user_relationship_page',
  user_pending_follow_request_page = 'user_pending_follow_request_page',
  community_notification_page = 'community_notification_page',
  community_posts_notification_page = 'community_posts_notification_page',
  community_comments_notification_page = 'community_comments_notification_page',
  community_stories_notification_page = 'community_stories_notification_page',
  community_livestreams_notification_page = 'community_livestreams_notification_page',
}
export enum ComponentID {
  content_report_reason = 'content_report_reason',
  EditComment = 'edit_comment_component',
  HyperLinkConfig = 'hyper_link_config_component',
  CommentTray = 'comment_tray_component',
  StoryTab = 'story_tab_component',
  WildCardComponent = '*',
  top_navigation = 'top_navigation',
  empty_newsfeed = 'empty_newsfeed',
  my_communities = 'my_communities',
  newsfeed_component = 'newsfeed_component',
  global_feed_component = 'global_feed_component',
  post_content = 'post_content',
  top_search_bar = 'top_search_bar',
  community_search_result = 'community_search_result',
  media_attachment = 'media_attachment',
  detailed_media_attachment = 'detailed_media_attachment',
  create_post_menu = 'create_post_menu',
  explore_empty = 'explore_empty',
  explore_community_empty = 'explore_community_empty',
  explore_community_categories = 'explore_community_categories',
  recommended_communities = 'recommended_communities',
  trending_communities = 'trending_communities',
  community_header = 'community_header',
  community_feed = 'community_feed',
  community_pin = 'community_pin',
  community_image_feed = 'community_image_feed',
  community_video_feed = 'community_video_feed',
  thumbnail_action = 'thumbnail_action',
  pending_post_list = 'pending_post_list',
  user_profile_header = 'user_profile_header',
  user_feed = 'user_feed',
  user_image_feed = 'user_image_feed',
  user_video_feed = 'user_video_feed',
}
export enum ElementID {
  submit_button = 'submit_button',
  CloseBtn = 'close_button',
  AspectRatioBtn = 'aspect_ratio_button',
  StoryHyperLinkBtn = 'story_hyperlink_button',
  HyperLink = 'hyper_link',
  ShareStoryBtn = 'share_story_button',
  ProgressBar = 'progress_bar',
  OverFlowMenu = 'overflow_menu',
  StoryImpressionBtn = 'story_impression_button',
  StoryCommentBtn = 'story_comment_button',
  StoryReactionBtn = 'story_reaction_button',
  CreateNewStoryBtn = 'create_new_story_button',
  SpeakerBtn = 'speaker_button',
  CancelBtn = 'cancel_button',
  SaveBtn = 'save_button',
  DoneBtn = 'done_button',
  StoryRing = 'story_ring',
  WildCardElement = '*',
  header_label = 'header_label',
  global_search_button = 'global_search_button',
  post_creation_button = 'post_creation_button',
  newsfeed_button = 'newsfeed_button',
  explore_button = 'explore_button',
  my_communities_button = 'my_communities_button',
  illustration = 'illustration',
  title = 'title',
  description = 'description',
  explore_communities_button = 'explore_communities_button',
  create_community_button = 'create_community_button',
  community_avatar = 'community_avatar',
  community_display_name = 'community_display_name',
  community_private_badge = 'community_private_badge',
  community_official_badge = 'community_official_badge',
  community_category_name = 'community_category_name',
  community_members_count = 'community_members_count',
  back_button = 'back_button',
  menu_button = 'menu_button',
  moderator_badge = 'moderator_badge',
  timestamp = 'timestamp',
  post_content_view_count = 'post_content_view_count',
  reaction_button = 'reaction_button',
  comment_button = 'comment_button',
  share_button = 'share_button',
  search_icon = 'search_icon',
  clear_button = 'clear_button',
  cancel_button = 'cancel_button',
  create_new_post_button = 'create_new_post_button',
  edit_post_button = 'edit_post_button',
  edit_post_title = 'edit_post_title',
  camera_button = 'camera_button',
  image_button = 'image_button',
  video_button = 'video_button',
  file_button = 'file_button',
  detailed_button = 'detailed_button',
  create_post_button = 'create_post_button',
  create_story_button = 'create_story_button',
  create_poll_button = 'create_poll_button',
  create_livestream_button = 'create_livestream_button',
  my_timeline_avatar = 'my_timeline_avatar',
  my_timeline_text = 'my_timeline_text',
  close_button = 'close_button',
  explore_trending_title = 'explore_trending_title',
  explore_recommended_title = 'explore_recommended_title',
  explore_empty_image = 'explore_empty_image',
  explore_create_community = 'explore_create_community',
  category_chip = 'category_chip',
  community_card_image = 'community_card_image',
  community_join_button = 'community_join_button',
  community_joined_button = 'community_joined_button',
  community_category = 'community_category',
  community_member_count = 'community_member_count',
  community_row_image = 'community_row_image',
  all_categories_title = 'all_categories_title',
  category_row_image = 'category_row_image',
  category_row_name = 'category_row_name',
  category_title = 'category_title',
  community_empty_title = 'community_empty_title',
  community_empty_image = 'community_empty_image',
  community_cover = 'community_cover',
  community_name = 'community_name',
  community_verify_badge = 'community_verify_badge',
  community_description = 'community_description',
  community_info = 'community_info',
  community_pending_post = 'community_pending_post',
  community_profile_tab = 'community_profile_tab',
  community_create_post_button = 'community_create_post_button',
  non_member_section = 'non_member_section',
  start_livestream_button = 'start_livestream_button',
  add_thumbnail_button = 'add_thumbnail_button',
  switch_camera_button = 'switch_camera_button',
  end_live_stream_button = 'end_live_stream_button',
  live_timer_status = 'live_timer_status',
  total_view = 'total_view',
  cancel_create_livestream_button = 'cancel_create_livestream_button',
  livestream_terminated_action_button = 'livestream_terminated_action_button',
  change_thumbnail_button = 'change_thumbnail_button',
  delete_thumbnail_button = 'delete_thumbnail_button',
  poll_question_title = 'poll_question_title',
  poll_options_title = 'poll_options_title',
  poll_options_desc = 'poll_options_desc',
  poll_add_option_button = 'poll_add_option_button',
  poll_duration_title = 'poll_duration_title',
  poll_duration_desc = 'poll_duration_desc',
  poll_multiple_selection_title = 'poll_multiple_selection_title',
  poll_multiple_selection_desc = 'poll_multiple_selection_desc',
  community_name_title = 'community_name_title',
  community_about_title = 'community_about_title',
  community_category_title = 'community_category_title',
  community_privacy_title = 'community_privacy_title',
  community_privacy_public_icon = 'community_privacy_public_icon',
  community_privacy_public_title = 'community_privacy_public_title',
  community_privacy_public_description = 'community_privacy_public_description',
  community_privacy_private_icon = 'community_privacy_private_icon',
  community_privacy_private_title = 'community_privacy_private_title',
  community_privacy_private_description = 'community_privacy_private_description',
  community_add_member_title = 'community_add_member_title',
  community_add_member_button = 'community_add_member_button',
  community_create_button = 'community_create_button',
  community_edit_title = 'community_edit_title',
  community_edit_button = 'community_edit_button',
  edit_profile = 'edit_profile',
  members = 'members',
  post_permission = 'post_permission',
  story_setting = 'story_setting',
  notifications = 'notifications',
  leave_community = 'leave_community',
  close_community = 'close_community',
  close_community_description = 'close_community_description',
  posts_tab_description = 'posts_tab_description',
  posts_button_tab = 'posts_button_tab',
  post_accept_button = 'post_accept_button',
  post_decline_button = 'post_decline_button',
  pin_badge = 'pin_badge',
  announcement_badge = 'announcement_badge',
  user_display_name_title = 'user_display_name_title',
  user_about_title = 'user_about_title',
  update_user_profile_button = 'update_user_profile_button',
  create_user_profile_button = 'create_user_profile_button',
  unblock_user_button = 'unblock_user_button',
  follow_user_button = 'follow_user_button',
  following_user_button = 'following_user_button',
  pending_user_button = 'pending_user_button',
  user_avatar = 'user_avatar',
  user_name = 'user_name',
  user_description = 'user_description',
  user_following = 'user_following',
  user_follower = 'user_follower',
  user_feed_tab_button = 'user_feed_tab_button',
  user_image_feed_tab_button = 'user_image_feed_tab_button',
  user_video_feed_tab_button = 'user_video_feed_tab_button',
  empty_user_feed = 'empty_user_feed',
  private_user_feed = 'private_user_feed',
  private_user_feed_info = 'private_user_feed_info',
  blocked_user_feed = 'blocked_user_feed',
  blocked_user_feed_info = 'blocked_user_feed_info',
  empty_user_image_feed = 'empty_user_image_feed',
  private_user_image_feed = 'private_user_image_feed',
  private_user_image_feed_info = 'private_user_image_feed_info',
  blocked_user_image_feed = 'blocked_user_image_feed',
  blocked_user_image_feed_info = 'blocked_user_image_feed_info',
  empty_user_video_feed = 'empty_user_video_feed',
  private_user_video_feed = 'private_user_video_feed',
  private_user_video_feed_info = 'private_user_video_feed_info',
  blocked_user_video_feed = 'blocked_user_video_feed',
  blocked_user_video_feed_info = 'blocked_user_video_feed_info',
  copy_link = 'copy_link',
  share_link = 'share_link',
}

export interface UiKitConfigKeys {
  title?: string;
  text?: string;
  back_icon?: string;
  resolution?: string;
  close_icon?: string;
  background_color?: string;
  aspect_ratio_icon?: string;
  hyperlink_button_icon?: string;
  share_icon?: string;
  hide_avatar?: boolean;
  progress_color?: [string, string];
  overflow_menu_icon?: string;
  impression_icon?: string;
  comment_icon?: string;
  reaction_icon?: string;
  create_new_story_icon?: string;
  mute_icon?: string;
  unmute_icon?: string;
  cancel_icon?: string;
  cancel_button_text?: string;
  save_icon?: string;
  save_button_text?: string;
  done_icon?: string;
  done_button_text?: string;
  icon?: string;
  image?: string;
}

export enum DefaultConfigID {
  SelectTargetPage = 'select_target_page/*/*',
  CameraPage = 'camera_page/*/*',
  StoryPage = 'story_page/*/*',
  CreateStoryPage = 'create_story_page/*/*',
  EditComment = '*/edit_comment_component/*',
  HyperLinkConfig = '*/hyper_link_config_component/*',
  CommentTray = '*/comment_tray_component/*',
  StoryTab = '*/story_tab_component/*',
  BackBtnOnSelectTargetPage = 'select_target_page/*/back_button',
  CloseBtnOnCameraPage = 'camera_page/*/close_button',
  BackBtnOnCreateStoryPage = 'create_story_page/*/back_button',
  AspectRatioBtnOnCreateStoryPage = 'create_story_page/*/aspect_ratio_button',
  StoryHyperLinkBtnOnCreateStoryPage = 'create_story_page/*/story_hyperlink_button',
  HyperLinkOnCreateStoryPage = 'create_story_page/*/hyper_link',
  ShareStoryBtnOnCreateStoryPage = 'create_story_page/*/share_story_button',
  ProgressBarOnCreateStoryPage = 'story_page/*/progress_bar',
  OverFlowMenuOnStoryPage = 'story_page/*/overflow_menu',
  CloseBtnOnStoryPage = 'story_page/*/close_button',
  StoryImpressionBtnOnStoryPage = 'story_page/*/story_impression_button',
  StoryCommentBtnOnStoryPage = 'story_page/*/story_comment_button',
  StoryReactionBtnOnStoryPage = 'story_page/*/story_reaction_button',
  CreateNewStoryBtnOnStoryPage = 'story_page/*/create_new_story_button',
  SpeakerBtnOnStoryPage = 'story_page/*/speaker_button',
  CancelBtnOnEditComment = '*/edit_comment_component/cancel_button',
  SaveBtnOnEditComment = '*/edit_comment_component/save_button',
  DoneBtnOnHyperLinkConfig = '*/hyper_link_config_component/done_button',
  CancelBtnOnHyperLinkConfig = '*/hyper_link_config_component/cancel_button',
  StoryRingOnStoryTab = '*/story_tab_component/story_ring',
  CreateNewStoryBtnOnStoryTab = '*/story_tab_component/create_new_story_button',
  CloseBtnOnAllPage = '*/*/close_button',
}
